### ISSUE TITLE
Android doesn't obtain IP from hotspot

### ISSUE THREAD

**Issue by schweini** [davesteele/comitup#83] opened 2019-12-01 22:38 UTC
I can connect to the AP from my windows laptop, but Android seems to be stuck at "Obtaining IP address" (Pixel XL, Android 10)

**Comment by davesteele** [comment] 2019-12-01 23:30
I can't replicate from Android 9. The initial experience is usually better if you start from a Comitup image. 

Normally, I'd blame DHCP port contention for the problem, but, in that case, Windows wouldn't work either. If you find the cause of the problem, Let me know.

**Comment by schweini** [comment] 2019-12-01 23:42
Any tips which log files to keep an eye on to identify the problem?

**Comment by davesteele** [comment] 2019-12-02 00:43
Most activity is in syslog.

**Comment by davesteele** [comment] 2020-06-09 13:02
This is likely DHCP server contention. Not a problem in the disk image, and addressed in the package install directions.

**Closed by davesteele** 2020-06-09 13:02 UTC
